### PR TITLE
Error check fwrite

### LINKED ISSUE #6: No error messege when not enough disk space
Silently fails and generates short coredump and creates confustion

### PR DESCRIPTION
**Pull request by santoshx**
Fixes #6

### CODE REVIEW

File: vm2core/src/PartitionState.cpp [hunk 1]
```diff
@@ -159,6 +159,14 @@ void VmPartitionState::FillElfNote(BYTE *buf, const char *name, void *data,
 	memcpy(buf, data, note->n_descsz);
 }
 
+void VmPartitionState::FwriteErrCheck(const void *buffer, size_t size, size_t count, FILE *stream) {
+    int ret = fwrite(buffer, size, count, stream);
+    if(ret < count) {
+        wprintf(L"Failed to write to file. Likly not enough disk space.\n");
```
Comment (seansp) [inline vm2core/src/PartitionState.cpp]: typo -- 'likely'

**Comment by dcui** [comment]
Looks good to me. Thanks for the fix!

File: vm2core/src/PartitionState.cpp [hunk 2]
```diff
@@ -159,6 +159,14 @@ void VmPartitionState::FillElfNote(BYTE *buf, const char *name, void *data,
 	memcpy(buf, data, note->n_descsz);
 }
 
+void VmPartitionState::FwriteErrCheck(const void *buffer, size_t size, size_t count, FILE *stream) {
+    int ret = fwrite(buffer, size, count, stream);
+    if(ret < count) {
+        wprintf(L"Failed to write to file. Likly not enough disk space.\n");
+        exit(EXIT_FAILURE);
```
Comment (seansp) [inline vm2core/src/PartitionState.cpp]: Changes flow to terminate here but looks like this is a good place to stop.
